apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-integration-service
  namespace: platform-services
  labels:
    app.kubernetes.io/part-of: internal-trust
    app.kubernetes.io/component: service
