apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-shared-resources
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # REPLACE: with your Git repository URL
    repoURL: https://git.mydomain.no/platform/acm-workload-identity.git
    targetRevision: main
    path: shared
  destination:
    server: https://kubernetes.default.svc
    namespace: acm-policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
