apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - managed-cluster-set-binding.yaml
  - placements/placement-oidc-federation.yaml
  - placements/placement-internal-trust-operator.yaml
  - placements/placement-internal-trust-service.yaml
  - placements/placement-hub.yaml
  - placements/placement-oidc-issuer-change.yaml
  - placement-bindings.yaml
