apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-oidc-federation
  namespace: acm-policies
spec:
  clusterSets:
    - all-openshift-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: oidc-federation
              operator: In
              values:
                - "enabled"
            - key: vendor
              operator: In
              values:
                - "OpenShift"
