apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-review-sa
  namespace: platform-automation
  labels:
    app.kubernetes.io/part-of: internal-trust
    app.kubernetes.io/component: token-review
