apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataclassification-agent
  namespace: platform-automation
  labels:
    app.kubernetes.io/part-of: internal-trust
    app.kubernetes.io/component: operator
